name: Request support
description: I need to request support from the Software Engineering Team

body:
  - type: markdown
    attributes:
      value: |
        This is a form to request support from the University of Colorado Department of Biomedical Informatics **Software Engineering Team** (SET).

        [⭐ **List of our services and current team members** ⭐](https://cu-dbmi.github.io/set-website/about)

        **If you don't have a GitHub account**, you can instead use [this Google Form](https://forms.gle/x5xHTXduRHERvhhS9), which will create a request here for you.

        **This form is not meant to be a barrier to support**, it is only meant to save time and allow us to better help you by asking a standard set of questions and tracking requests in an organized way. If you already have an established contact and agreement with a specific SET developer, you can continue to communicate directly with them.

        This support request does not become a rigid, set-in-stone contract. However, we do ask that you help us keep it up to date by posting a new comment or editing the original request whenever there are significant changes in work or scope.

        **This request will be publicly visible after you submit it**. You can look at what support others have requested [here](https://github.com/CU-DBMI/set-intake/issues). If you need to make a private request, please contact [Audrey Wen](mailto:audrey.wen@cuanschutz.edu) with the same info as below. Or you can fill out the form but omit details that you want to keep private (such as funding), and send the missing info to Audrey directly.

  - type: input
    id: group
    attributes:
      label: Group
      description: The lab, faculty member, PI, team, org, or group this project is primarily for.
      placeholder: e.g. Greene Lab
    validations:
      required: true

  - type: textarea
    id: contact
    attributes:
      label: Contact info
      description: Contact and name info for key parties for the project.
      placeholder: |
        E.g.:
        Casey Greene, PI, casey@greenelab.com, @caseygreene on Slack
        John Doe, project lead, john.doe@fake.com, @johndoe on Slack
    validations:
      required: true

  - type: dropdown
    id: category
    attributes:
      label: Type of support
      description: Which of these best describe the type of support you need?
      options:
        - Short/medium-term project (ongoing)
        - Debugging/troubleshooting (one-off)
        - Consulting/education (one-off)
        - Other
      multiple: true
      default: 0
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Description
      description: |
        Describe the specific support you need from SET. E.g.:
        - What is roughly the scope of the support? Short, medium, or long-term? Simple or complex? One-off or on-going?
        - What do you need help debugging/troubleshooting?
        - What questions do you want to ask? What do you want to learn about?
        - What kind of [project](https://cu-dbmi.github.io/set-website/about#what-we-do) do you have?
            - Which parts do you need help with? E.g design, implementation, debugging, automation, testing, maintenance, etc.
            - What are the requirements? What is the "minimum viable product"? What are the different phases of the project?
        - Does any data you're handling fall under [confidential classification](https://www.cu.edu/security/data-classification)? **Does your support involve data covered by [HIPAA](https://www.cdc.gov/phlp/publications/topic/hipaa.html)**, e.g. protected health information (PHI)?
    validations:
      required: true

  - type: textarea
    id: repos
    attributes:
      label: Links to code
      description: |
        Link to any existing code you have on e.g. GitHub, GitLab, Bitbucket, etc., and provide us the appropriate permissions to view it ([please invite all of our team members](https://cu-dbmi.github.io/set-website/about#the-team)). This will help us to proactively answer questions, estimate time, find solutions, contribute fixes, etc.
      placeholder: |
        E.g.:
        https://github.com/greenelab/some-repo

  - type: textarea
    id: workflow
    attributes:
      label: Workflow
      description: |
        Describe your software workflow and practices. E.g.:
        - Do you use git and GitHub for tracking code?
        - What operating system do you use?
        - What programming languages, package managers, and notable libraries do you use?
        - What IDE/editor or other tools do you use?

  - type: textarea
    id: timeline
    attributes:
      label: Timeline
      description: |
        Describe all of your hard and soft deadlines for specific parts of the support. E.g.:
        - When does your issue need to be fixed or question answered by?
        - When does your project need to be done? What are the milestones?

  - type: textarea
    id: funding
    attributes:
      label: Funding
      description: |
        For small/one-off efforts, the department enables SET to offer support at no cost. For larger/ongoing efforts, you'll likely be asked to cover some or all of the cost with your own grant (or other) funds. If applicable, describe your funding situation in detail.

        **Omit if you want to keep this info private** (see note above).
